### ISSUE TITLE
Initial bug

### ISSUE THREAD

**Issue by shaiguitar** [otakup0pe/hcvswitch#1]
Just for first time use.

```
shai@adsk-lappy ~/r/virtela [master] ± % hcvswitch adsk_prod
head: /Users/shai/.hcvaccount: No such file or directory
```

**Comment by shaiguitar** [comment]
Also, having a "current" indicator would be nice:

```
shai@adsk-lappy ~   % hcvlist
adsk_stage
adsk_prod
adsk_dev
```

Maybe a "*" or "-" for the current one in use.

**Comment by otakup0pe** [comment]
```
$ rm ~/.hcvaccount
$ hcvswitch foo
$ hcvlist
  bar
* foo
  baz
```

Both these things got handled in https://github.com/otakup0pe/hcvswitch/commit/9b2da00fbd149feeca37fb9deecdb9f8cdd1ac7a
